# Generated by Django 4.0.5 on 2023-08-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
            ],
        ),
    ]
